import type { SkillDef } from '@/core/types'

export const DEMO_SKILLS: SkillDef[] = [
  {
    id: 'basic_attack',
    name: '斩击',
    type: 'weaponskill',
    castTime: 0,
    cooldown: 0,
    gcd: true,
    targetType: 'single',
    range: 5,
    effects: [{ type: 'damage', potency: 2 }],
  },
  {
    id: 'heavy_swing',
    name: '重劈',
    type: 'weaponskill',
    castTime: 0,
    cooldown: 0,
    gcd: true,
    targetType: 'single',
    range: 5,
    effects: [{ type: 'damage', potency: 3.5 }],
  },
  {
    id: 'overpower',
    name: '超压斧',
    type: 'weaponskill',
    castTime: 0,
    cooldown: 0,
    gcd: true,
    targetType: 'aoe',
    range: 0,
    zones: [{
      anchor: { type: 'caster' },
      direction: { type: 'caster_facing' },
      shape: { type: 'fan', radius: 8, angle: 120 },
      telegraphDuration: 0,
      resolveDelay: 0,
      hitEffectDuration: 300,
      effects: [{ type: 'damage', potency: 1.5 }],
    }],
  },
  {
    id: 'rage_burst',
    name: '战嚎',
    type: 'ability',
    castTime: 0,
    cooldown: 30000,
    gcd: false,
    targetType: 'aoe',
    range: 0,
    zones: [{
      anchor: { type: 'caster' },
      direction: { type: 'none' },
      shape: { type: 'circle', radius: 6 },
      telegraphDuration: 0,
      resolveDelay: 0,
      hitEffectDuration: 300,
      effects: [{ type: 'damage', potency: 5 }],
    }],
  },
]
